apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "karapace-test"
  namespace: "nais"
spec:
  image: "{{image}}"
  liveness:
    path: "/"
  startup:
    failureThreshold: 10
    initialDelay: 20
    path: "/"
  readiness:
    path: "/brokers"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  kafka:
    pool: nav-dev
