apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "karapace-test"
  namespace: "aura"
  labels:
    team: "aura"
spec:
  image: {{image}}
  port: 8081
  liveness:
    path: "/"
    port: 8081
  readiness:
    path: "/brokers"
    port: 8081
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  kafka:
    pool: nav-dev
