apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  labels:
    team: nais
  name: karapace-test
  namespace: nais
spec:
  acl:
  - access: readwrite
    application: "*"
    team: nais
  config:
    cleanupPolicy: delete
    maxMessageBytes: 1048588
    minimumInSyncReplicas: 2
    partitions: 3
    replication: 3
    retentionBytes: -1
    retentionHours: 24
    segmentHours: 168
  pool: nav-dev
