name: Create docker image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
    - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: "actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac" # ratchet:actions/checkout@v3
      - uses: nais/platform-build-push-sign@main
        id: build-push-sign
        with:
          name: karapace
          google_service_account: gh-karapace
          push: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: "${{ steps.build-push-sign.outputs.tag }}"
  deploy:
    name: "deploy for testing"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: "actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac" # ratchet:actions/checkout@v2
      - uses: nais/deploy/actions/deploy@b2c5fbf3fc4d777a36b311da70d9ff429416b552 # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          VAR: image=${{ needs.build.outputs.image }}
